### ISSUE TITLE
Broken image upload on ingest form

### ISSUE THREAD

**Issue by straleyb** [OregonDigital/OD2#200]
### Descriptive summary

There is currently a bug where uploading a file is broken. Its broken in the conversion of the file on the ingest form. When you choose a file to upload and click the upload button it gives this error.
```
Encoding::UndefinedConversionError ("\xFF" from ASCII-8BIT to UTF-8):
server_1           |
server_1           | libhoney (1.11.0) lib/libhoney/log_transmission.rb:24:in `add'
server_1           | libhoney (1.11.0) lib/libhoney/client.rb:221:in `send_event'
server_1           | libhoney (1.11.0) lib/libhoney/event.rb:93:in `send_presampled'
server_1           | libhoney (1.11.0) lib/libhoney/event.rb:84:in `send'
```
This is an error possibly with paperclip or carrierwave or honeycomb. This is a bug and is blocking ingest on master.

You should be able to upload an image.

### QA

Upload a file on the ingest form should work.

**Comment by straleyb** [comment]
This was fixed by removing the debug option from the docker file.
