### ISSUE TITLE
Add TFDDBasins ONS vocab to Location CV

### ISSUE THREAD

**Issue by wickr** [OregonDigital/OD2#2794]
### Descriptive summary

The TFDDbasins vocab from opaquenamespace.org needs to be added to the Location CV, particularly for use in the Water Basin field. This was a relatively late addition to the OD1 codebase and not originally on the MAP, but it's added now.

The freshwater treaties documents frequently use this vocab along with GeoNames in the Water Basin property.

Since the Location CV overrides the Hyrax one, I don't think it formally restricts what URIs can be added (beyond the GeoNames in type-ahead). So the opaquenamespace.org URIs can be added, but they currently fail at label parsing for in the Location CV:

```
Traceback (most recent call last):
       12: from (irb):316
       11: from (irb):316:in `each'
       10: from (irb):320:in `block in irb_binding'
        9: from app/indexers/document_indexer.rb:6:in `generate_solr_document'
        8: from app/indexers/generic_indexer.rb:17:in `generate_solr_document'
        7: from app/indexers/concerns/oregon_digital/indexing_dates_behavior.rb:9:in `generate_solr_document'
        6: from app/indexers/oregon_digital/deep_indexing_service.rb:21:in `add_assertions'
        5: from app/indexers/oregon_digital/deep_indexing_service.rb:43:in `fetch_external'
        4: from app/indexers/oregon_digital/deep_indexing_service.rb:43:in `each'
        3: from app/indexers/oregon_digital/deep_indexing_service.rb:44:in `block in fetch_external'
        2: from app/indexers/oregon_digital/deep_indexing_service.rb:52:in `block (2 levels) in fetch_external'
        1: from lib/hyrax/controlled_vocabularies/location.rb:44:in `rdf_label'
NoMethodError (undefined method `split' for #<RDF::Literal:0x1ea0c8("Colorado"@en)>)
```

OD1 example item link: https://od1.oregondigital.org/catalog/oregondigital:gb19fr166#page/1/mode/1up
OD2 work link that currently errors: https://prod.oregondigital.org/concern/documents/gb19fr166
example URI: http://opaquenamespace.org/ns/TFDDbasins/CLDO

### Expected behavior

TFDD basin URIs are allowed in fields powered by the Location CV, and labels fetched appropriately (no hierarchy or additions needed beyond what is fetched).

**Comment by wickr** [comment]
QA pass.
Added TFDDBasin URIs in both Location and Water Basin fields, along with a GeoNames URI in Location.

https://staging.oregondigital.org/concern/documents/3j3332278?locale=en#metadata
![image](https://user-images.githubusercontent.com/2293544/221321534-cf8535b3-1536-41f7-b856-ffa7e0bc3bf3.png)
