### ISSUE TITLE
Image failed to save

### ISSUE THREAD

**Issue by revgum** [OregonDigital/OD2#290]
### Descriptive summary

On `Staging`, an Image is unable to save and fails with the following exception

```
I, [2019-01-15T22:52:37.119474 #33]  INFO -- : [7e41de89-681b-409e-977d-554cfe95fd02] Completed 500 Internal Server Error in 231ms (ActiveRecord: 12.8ms)
F, [2019-01-15T22:52:37.122411 #33] FATAL -- : [7e41de89-681b-409e-977d-554cfe95fd02]
F, [2019-01-15T22:52:37.122599 #33] FATAL -- : [7e41de89-681b-409e-977d-554cfe95fd02] ActiveFedora::UnknownAttributeError (unknown attribute 'date_created' for Image.):
F, [2019-01-15T22:52:37.127253 #33] FATAL -- : [7e41de89-681b-409e-977d-554cfe95fd02]
F, [2019-01-15T22:52:37.127404 #33] FATAL -- : [7e41de89-681b-409e-977d-554cfe95fd02] active-fedora (11.5.4) lib/active_fedora/attribute_assignment.rb:50:in `_assign_attribute'
[7e41de89-681b-409e-977d-554cfe95fd02] active-fedora (11.5.4) lib/active_fedora/attribute_assignment.rb:45:in `block in _assign_attributes'
[7e41de89-681b-409e-977d-554cfe95fd02] active-fedora (11.5.4) lib/active_fedora/attribute_assignment.rb:44:in `each'
[7e41de89-681b-409e-977d-554cfe95fd02] active-fedora (11.5.4) lib/active_fedora/attribute_assignment.rb:44:in `_assign_attributes'
[7e41de89-681b-409e-977d-554cfe95fd02] active-fedora (11.5.4) lib/active_fedora/attribute_assignment.rb:38:in `assign_attributes'
[7e41de89-681b-409e-977d-554cfe95fd02] active-fedora (11.5.4) lib/active_fedora/attribute_assignment.rb:9:in `attributes='
[7e41de89-681b-409e-977d-554cfe95fd02] active-fedora (11.5.4) lib/active_fedora/attributes/serializers.rb:24:in `attributes='
[7e41de89-681b-409e-977d-554cfe95fd02] /usr/local/bundle/bundler/gems/hyrax-c0699505fc89/app/actors/hyrax/actors/base_actor.rb:72:in `apply_save_data_to_curation_concern'
[7e41de89-681b-409e-977d-554cfe95fd02] /usr/local/bundle/bundler/gems/hyrax-c0699505fc89/app/actors/hyrax/actors/base_actor.rb:20:in `create'
[7e41de89-681b-409e-977d-554cfe95fd02] /usr/local/bundle/bundler/gems/hyrax-c0699505fc89/app/actors/hyrax/actors/model_actor.rb:17:in `create'
```

**Comment by CGillen** [comment]
PR Merged. @jechols & @revgum tested and deployed to staging.
#307 & #308 opened as a result of discovering and diagnosing this issue. Hopefully those issues will prevent something like this happening again.
