### ISSUE TITLE
Search on Staging is not working

### ISSUE THREAD

**Issue by revgum** [OregonDigital/OD2#463]
### Descriptive summary

Search fails on staging, here is the log with the error.

```
E, [2019-04-03T19:06:28.623680 #31] ERROR -- : [1ef1a2ae-18c1-4878-831d-db6188b2803c] RSolr::Error::Http - 414 Request-URI Too Long
Error: reason: URI Too Long

URI: http://solr.default.svc.cluster.local:8983/solr/staging/select?wt=json&qt=search&facet.field=human_readable_type_sim&facet.field=file_format_sim&facet.field=member_of_collections_ssim&facet.field=generic_type_sim&facet.field=has_number_sim&facet.field=is_volume_sim&facet.field=award_date_sim&facet.field=box_name_sim&facet.field=creator_display_sim&facet.field=exhibit_sim&facet.field=folder_name_sim&facet.field=folder_number_sim&facet.field=former_owner_sim&facet.field=keyword_sim&facet.field=language_sim&facet.field=license_sim&facet.field=location_sim&facet.field=oembed_url_sim&facet.field=ranger_district_sim&facet.field=relation_sim&facet.field=resource_type_sim&facet.field=rights_statement_sim&facet.field=series_name_sim&facet.field=series_number_sim&facet.field=set_sim&facet.field=water_basin_sim&facet.field=arranger_label_sim&facet.field=artist_label_sim&facet.field=author_label_sim&facet.field=based_near_label_sim&facet.field=cartographer_label_sim&facet.field=collector_label_sim&facet.field=composer_label_sim&facet.field=contributor_label_sim&facet.field=creator_label_sim&facet.field=cultural_context_label_sim&facet.field=dedicatee_label_sim&facet.field=designer_label_sim&facet.field=donor_label_sim&facet.field=editor_label_sim&facet.field=ethnographic_term_label_sim&facet.field=family_label_sim&facet.field=format_label_sim&facet.field=genus_label_sim&facet.field=illustrator_label_sim&facet.field=institution_label_sim&facet.field=interviewee_label_sim&facet.field=interviewer_label_sim&facet.field=local_collection_name_label_sim&facet.field=lyricist_label_sim&facet.field=military_branch_label_sim&facet.field=order_label_sim&facet.field=owner_label_sim&facet.field=patron_label_sim&facet.field=photographer_label_sim&facet.field=phylum_or_division_label_sim&facet.field=print_maker_label_sim&facet.field=publisher_label_sim&facet.field=recipient_label_sim&facet.field=repository_label_sim&facet.field=scribe_label_sim&facet.field=species_label_sim&facet.field=style_or_period_label_sim&facet.field=subject_label_sim&facet.field=taxon_class_label_sim&facet.field=tgn_label_sim&facet.field=transcriber_label_sim&facet.field=translator_label_sim&facet.field=workType_label_sim&&&fq=%28%7B%21terms+f%3Dedit_access_group_ssim%7Dpublic%29+OR+%28%7B%21terms+f%3Ddiscover_access_group_ssim%7Dpublic%29+OR+%28%7B%21terms+f%3Dread_access_group_ssim%7Dpublic%29&fq=%7B%21terms+f%3Dhas_model_ssim%7DGeneric%2CImage%2CVideo%2CDocument%2CAudio%2CCollection&fq=-suppressed_bsi%3Atrue&fq=%28%7B%21terms+f%3Dedit_access_group_ssim%7Dpublic%29+OR+%28%7B%21terms+f%3Ddiscover_access_group_ssim%7Dpublic%29+OR+%28%7B%21terms+f%3Dread_access_group_ssim%7Dpublic%29&fq=-suppressed_bsi%3Atrue&&rows=10&qf=contained_in_journal_tesim+first_line_tesim+first_line_chorus_tesim+has_number_tesim+host_item_tesim+instrumentation_tesim+is_volume_tesim+larger_work_tesim+number_of_pages_tesim+table_of_contents_tesim+abstract_tesim+accepted_name_usage_tesim+access_restrictions_tesim+accession_number_tesim+acquisition_date_tesim+alternative_tesim+art_series_tesim+award_tesim+award_date_tesim+barcode_tesim+biographical_information_tesim+box_tesim+box_name_tesim+box_number_tesim+canzoniere_poems_tesim+citation_tesim+collected_date_tesim+compass_direction_tesim+contents_tesim+conversion_tesim+copy_location_tesim+copyright_claimant_tesim+cover_description_tesim+coverage_tesim+creator_display_tesim+current_repository_id_tesim+date_tesim+date_created_tesim+date_digitized_tesim+description_tesim+description_of_manifestation_tesim+event_tesim+exhibit_tesim+extent_tesim+file_size_tesim+folder_name_tesim+folder_number_tesim+former_owner_tesim+gps_latitude_tesim+gps_longitude_tesim+has_finding_aid_tesim+has_part_tesim+has_version_tesim+higher_classification_tesim+hydrologic_unit_code_tesim+identification_verification_status_tesim+identifier_tesim+inscription_tesim+isPartOf_tesim+is_version_of_tesim+issued_tesim+item_locator_tesim+keyword_tesim+language_tesim+layout_tesim+legal_name_tesim+license_tesim+local_collection_id_tesim+location_tesim+location_copyshelf_location_tesim+longitude_latitude_identification_tesim+material_tesim+measurements_tesim+military_highest_rank_tesim+military_occupation_tesim+military_service_location_tesim+mode_of_issuance_tesim+mods_note_tesim+object_orientation_tesim+original_name_usage_tesim+physical_extent_tesim+place_of_production_tesim+primary_set_tesim+provenance_tesim+publication_place_tesim+ranger_district_tesim+relation_tesim+replaces_url_tesim+resource_type_tesim+rights_holder_tesim+rights_statement_tesim+scientific_name_authorship_tesim+series_name_tesim+series_number_tesim+set_tesim+source_tesim+source_condition_tesim+specimen_type_tesim+sports_team_tesim+state_or_edition_tesim+street_address_tesim+technique_tesim+temporal_tesim+tribal_classes_tesim+tribal_notes_tesim+tribal_terms_tesim+tribal_title_tesim+use_restrictions_tesim+view_date_tesim+water_basin_tesim+color_content_tesim+color_space_tesim+orientation_tesim+photograph_orientation_tesim+resolution_tesim+view_tesim+arranger_label_tesim+artist_label_tesim+author_label_tesim+based_near_label_tesim+cartographer_label_tesim+collector_label_tesim+common_name_label_tesim+composer_label_tesim+contributor_label_tesim+creator_label_tesim+cultural_context_label_tesim+dedicatee_label_tesim+designer_label_tesim+donor_label_tesim+editor_label_tesim+ethnographic_term_label_tesim+family_label_tesim+form_of_work_label_tesim+format_label_tesim+genus_label_tesim+illustrator_label_tesim+institution_label_tesim+interviewee_label_tesim+interviewer_label_tesim+local_collection_name_label_tesim+lyricist_label_tesim+military_branch_label_tesim+order_label_tesim+owner_label_tesim+patron_label_tesim+photographer_label_tesim+phylum_or_division_label_tesim+print_maker_label_tesim+publisher_label_tesim+recipient_label_tesim+repository_label_tesim+scribe_label_tesim+species_label_tesim+style_or_period_label_tesim+subject_label_tesim+taxon_class_label_tesim+tgn_label_tesim+transcriber_label_tesim+translator_label_tesim+workType_label_tesim+file_format_tesim+all_text_timv&pf=title_tesim&q=%7B%21lucene%7D_query_%3A%22%7B%21dismax+v%3D%24user_query%7D%22+_query_%3A%22%7B%21join+from%3Did+to%3Dfile_set_ids_ssim%7D%7B%21dismax+v%3D%24user_query%7D%22&facet=true&f.human_readable_type_sim.facet.limit=6&f.file_format_sim.facet.limit=6&f.member_of_collections_ssim.facet.limit=6&f.has_number_sim.facet.limit=6&f.is_volume_sim.facet.limit=6&f.award_date_sim.facet.limit=6&f.box_name_sim.facet.limit=6&f.creator_display_sim.facet.limit=6&f.exhibit_sim.facet.limit=6&f.folder_name_sim.facet.limit=6&f.folder_number_sim.facet.limit=6&f.former_owner_sim.facet.limit=6&f.keyword_sim.facet.limit=6&f.language_sim.facet.limit=6&f.license_sim.facet.limit=6&f.location_sim.facet.limit=6&f.oembed_url_sim.facet.limit=6&f.ranger_district_sim.facet.limit=6&f.relation_sim.facet.limit=6&f.resource_type_sim.facet.limit=6&f.rights_statement_sim.facet.limit=6&f.series_name_sim.facet.limit=6&f.series_number_sim.facet.limit=6&f.set_sim.facet.limit=6&f.water_basin_sim.facet.limit=6&f.arranger_label_sim.facet.limit=6&f.artist_label_sim.facet.limit=6&f.author_label_sim.facet.limit=6&f.based_near_label_sim.facet.limit=6&f.cartographer_label_sim.facet.limit=6&f.collector_label_sim.facet.limit=6&f.composer_label_sim.facet.limit=6&f.contributor_label_sim.facet.limit=6&f.creator_label_sim.facet.limit=6&f.cultural_context_label_sim.facet.limit=6&f.dedicatee_label_sim.facet.limit=6&f.designer_label_sim.facet.limit=6&f.donor_label_sim.facet.limit=6&f.editor_label_sim.facet.limit=6&f.ethnographic_term_label_sim.facet.limit=6&f.family_label_sim.facet.limit=6&f.format_label_sim.facet.limit=6&f.genus_label_sim.facet.limit=6&f.illustrator_label_sim.facet.limit=6&f.institution_label_sim.facet.limit=6&f.interviewee_label_sim.facet.limit=6&f.interviewer_label_sim.facet.limit=6&f.local_collection_name_label_sim.facet.limit=6&f.lyricist_label_sim.facet.limit=6&f.military_branch_label_sim.facet.limit=6&f.order_label_sim.facet.limit=6&f.owner_label_sim.facet.limit=6&f.patron_label_sim.facet.limit=6&f.photographer_label_sim.facet.limit=6&f.phylum_or_division_label_sim.facet.limit=6&f.print_maker_label_sim.facet.limit=6&f.publisher_label_sim.facet.limit=6&f.recipient_label_sim.facet.limit=6&f.repository_label_sim.facet.limit=6&f.scribe_label_sim.facet.limit=6&f.species_label_sim.facet.limit=6&f.style_or_period_label_sim.facet.limit=6&f.subject_label_sim.facet.limit=6&f.taxon_class_label_sim.facet.limit=6&f.tgn_label_sim.facet.limit=6&f.transcriber_label_sim.facet.limit=6&f.translator_label_sim.facet.limit=6&f.workType_label_sim.facet.limit=6&sort=score+desc%2C+system_create_dtsi+desc&user_query=test&defType=lucene&f.member_of_collection_ids_ssim.facet.matches=%5E%24

Backtrace: /usr/local/bundle/gems/rsolr-2.2.1/lib/rsolr/client.rb:206:in `rescue in execute'
usr/local/bundle/gems/rsolr-2.2.1/lib/rsolr/client.rb:196:in `execute'
/usr/local/bundle/gems/rsolr-2.2.1/lib/rsolr/client.rb:191:in `send_and_receive'
/usr/local/bundle/gems/blacklight-6.18.0/lib/blacklight/solr/repository.rb:38:in `block in send_and_receive'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/benchmarkable.rb:41:in `block in benchmark'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/usr/local/bundle/gems/activesupport-5.1.6.2/lib/active_support/benchmarkable.rb:41:in `benchmark'
/usr/local/bundle/gems/blacklight-6.18.0/lib/blacklight/solr/repository.rb:36:in `send_and_receive'
/usr/local/bundle/gems/blacklight-6.18.0/lib/blacklight/solr/repository.rb:22:in `search'
```

**Comment by revgum** [comment]
An example URL that will fail: http://staging.oregondigital.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q=oregon

**Comment by revgum** [comment]
@wickr suggests to compare the catalog controller for OD2 against ScholarsArchive

**Comment by CGillen** [comment]
QA:
- [ ] Search works

**Comment by vantuyls** [comment]
QA Fail, search for work titles of known works returns no results. 
Example: http://staging.oregondigital.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=Vogels

**Comment by vantuyls** [comment]
QA Fail, search for titles of known works returns no results. 
Example: http://staging.oregondigital.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=testing

**Comment by vantuyls** [comment]
QA Pass - search works as expected
