### ISSUE TITLE
license issue on show page

### ISSUE THREAD

**Issue by luisgreg99** [OregonDigital/OD2#793]
### Descriptive summary

Issues when testing `Baseball_jpegs` collection and `license` field:

a) The MAP https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0 specifies that `license` should be single value, but the metadata is set to multiple https://github.com/OregonDigital/OD2/blob/master/app/models/concerns/oregon_digital/generic_metadata.rb#L358 I tried changing the metadata to multiple set to false, but that resulted in 

```
[ActiveJob] [Hyrax::Migrator::Jobs::MigrateWorkJob] [64983578-84a6-4d91-a6f1-c34bfbb14e28] failed persisting work sx61dm57b, You attempted to set the property `license' of sx61dm57b to an enumerable value. However, this property is declared as singular. : ["/usr/local/bundle/gems/active-fedora-11.5.4/lib/active_fedora/attributes/property_builder.rb:49:in `license='", "/usr/local/bundle/gems/active-fedora-11.5.4/lib/active_fedora/attribute_assignment.rb:51:in `public_send'", "/usr/local/bundle/gems/active-fedora-11.5.4/lib/active_fedora/attribute_assignment.rb:51:in `_assign_attribute'",

```
It looks like the form already takes into account the fact that it's single, but it’s not consistent with generic_metadata.rb.

b) The show/edit page breaks when `license` comes in with `http://opaquenamespace.org/ns/rights/rr-f`. After debugging, it looks like we can simply add it to https://github.com/OregonDigital/OD2/blob/master/config/authorities/licenses.yml

```
diff --git a/config/authorities/licenses.yml b/config/authorities/licenses.yml
index 82e5ac1..cccfe1f 100644
--- a/config/authorities/licenses.yml
+++ b/config/authorities/licenses.yml
@@ -3,6 +3,9 @@ terms:
     - id: ""
       term: ""
       active: true
+    - id: http://opaquenamespace.org/ns/rights/rr-f
+      term: Rights Reserved - Free Access
+      active: true
     - id: http://creativecommons.org/licenses/by/3.0/us/
       term: Attribution 3.0 United States
       active: false
```
We just need to find out the proper `term` value, or should we update in OD1 and re-export the bag?

**Comment by luisgreg99** [comment]
There is a related comment about `license`: https://github.com/OregonDigital/hyrax-migrator/issues/70#issuecomment-494446440
